language: node_js
node_js:
  - 12.18.3
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run dev

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: github_pages

services: mongodb

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy
# deploy
# after_deploy