language: node_js
node_js:
  - 12.13.0
cache: npm

install:
  - npm ci

script:
  - npm test
  - npm run dev

services: mongodb

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
